# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20160505_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('ifile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share.NoteModel', verbose_name=b'article text')),
            ],
        ),
    ]
