# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlart',
            name='category',
            field=models.CharField(blank=True, choices=[(b'common', b'common')], max_length=100, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='htmlart',
            name='statue',
            field=models.CharField(blank=True, choices=[(b'publish', b'publish'), (b'draft', b'draft')], max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
