# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160415_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srcmodel',
            name='statue',
            field=models.CharField(blank=True, choices=[(b'publish', b'publish'), (b'draft', b'draft')], max_length=100, verbose_name='\u72b6\u6001'),
        ),
    ]
