# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160415_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlart',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='srcmodel',
            name='type',
            field=models.CharField(blank=True, choices=[(b'rst', b'rst')], max_length=100, verbose_name='\u7c7b\u578b'),
        ),
    ]
