# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160419_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='type',
            field=models.CharField(blank=True, choices=[(b'html', b'html'), (b'rst', b'rst'), (b'ck', b'ckEditor')], max_length=100, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='\u540d\u79f0'),
        ),
    ]
