# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160419_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=200, verbose_name='\u79f0\u547c')),
                ('comment', models.TextField(blank=True, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u540d\u79f0\uff08url\uff09'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='type',
            field=models.CharField(blank=True, choices=[(b'html', b'html'), (b'ck', b'ckEditor')], max_length=100, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='artcomment',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleModel', verbose_name='\u6587\u7ae0'),
        ),
    ]
