# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='order',
            field=models.CharField(default=b'1000', max_length=100, verbose_name='\u987a\u5e8f'),
        ),
        migrations.AlterField(
            model_name='artcomment',
            name='comment',
            field=models.TextField(default=b'', verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='artcomment',
            name='nickname',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u79f0\u547c'),
        ),
    ]
