# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='\u6807\u9898')),
                ('html', models.TextField(blank=True, verbose_name='html\u4ee3\u7801')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('statue', models.CharField(blank=True, max_length=100, verbose_name='\u72b6\u6001')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SrcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='\u7c7b\u578b')),
                ('src', models.TextField(blank=True, verbose_name='\u6e90\u4ee3\u7801')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65e5\u671f')),
                ('statue', models.CharField(blank=True, max_length=100, verbose_name='\u72b6\u6001')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='srcmodel',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='htmlart',
            name='src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.SrcModel', verbose_name='\u6e90\u6587\u4ef6'),
        ),
        migrations.AddField(
            model_name='htmlart',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
