# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160413_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlart',
            name='category',
            field=models.CharField(blank=True, choices=[(b'common', b'common'), (b'math', b'math')], max_length=100, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='htmlart',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='srcmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
