# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=400, verbose_name='label')),
                ('content', models.TextField(blank=True, verbose_name='content')),
            ],
        ),
    ]
