# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagebuilder', '0002_mobilepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepage',
            name='content',
            field=models.TextField(blank=True, verbose_name='content of'),
        ),
    ]
