# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-08 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('label', models.CharField(blank=True, max_length=300, verbose_name='label')),
                ('page_cls', models.CharField(blank=True, max_length=100, verbose_name='page class')),
                ('text', models.TextField(blank=True, verbose_name='content')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='status')),
            ],
        ),
    ]
