# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u79f0\u547c')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('text', models.TextField(blank=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
    ]
