# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_leavemsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemsg',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\u79f0\u547c'),
        ),
        migrations.AlterField(
            model_name='leavemsg',
            name='text',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
    ]
